name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        v1: $ {{ secrets.MY_SECRET_VAR }}
        v2: $ {{ secrets.MY_REPO_SECRET_VAR }}
        v3: $ {{ context.MY_CONTEXT_VAR }}
        v4: $ {{ MY_REPO_VAR }}
      run: ls -lA && source build.sh
