name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: MyEnv
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        v1: ${{ secrets.MY_SECRET_VAR }}
        v2: ${{ secrets.MY_REPO_SECRET_VAR }}
        v3: ${{ vars.MY_CONTEXT_VAR }}
        v4: ${{ vars.MY_REPO_VAR }}
      run: ls -lA && source build.sh
